---
# - name: restart webserver
#   service:
#     name: "{{ php_webserver_daemon }}"
#     state: restarted
#   notify: restart php-fpm
#   when: php_enable_webserver

- name: restart webserver
  ansible.builtin.shell: |
    nginx -s stop
    sleep 1
    nginx
  notify: restart php-fpm
  when: php_enable_webserver

- name: restart php-fpm
  ansible.builtin.command:
    cmd: |
      /etc/init.d/php7.4-fpm stop
      /etc/init.d/php7.4-fpm start
  when:
    - php_enable_php_fpm
    - not ansible_check_mode
      